#!/usr/bin/env bash
# Apply COGENTIA_MCP_JHN_* from workstation SoT (inseme/.env) onto fracta mcp-cogentia.
# Does not print the token. Run from a machine with ssh fracta + local inseme/.env.
set -euo pipefail

ROOT="${1:-}"
if [[ -z "$ROOT" ]]; then
  # default: monorepo layout
  ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
fi
ENV_FILE="${INSEME_ENV:-$ROOT/inseme/.env}"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "missing $ENV_FILE" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
# extract only the three vars without sourcing whole file (may have special chars)
TOKEN=$(grep -E '^COGENTIA_MCP_JHN_TOKEN=' "$ENV_FILE" | tail -1 | cut -d= -f2- | tr -d '\r')
MUTATE=$(grep -E '^COGENTIA_MCP_JHN_MUTATE=' "$ENV_FILE" | tail -1 | cut -d= -f2- | tr -d '\r')
URL=$(grep -E '^COGENTIA_MCP_URL=' "$ENV_FILE" | tail -1 | cut -d= -f2- | tr -d '\r')
set +a

if [[ -z "$TOKEN" ]]; then
  echo "COGENTIA_MCP_JHN_TOKEN empty in $ENV_FILE" >&2
  exit 1
fi
MUTATE="${MUTATE:-1}"
URL="${URL:-https://cogentia.fractavolta.com/mcp}"

echo "Applying JHN MCP token to fracta (mutate=$MUTATE, token_len=${#TOKEN})…"

ssh fracta "sudo mkdir -p /srv/cogentia/secrets /etc/systemd/system/mcp-cogentia.service.d
sudo tee /srv/cogentia/secrets/jhn-mcp.env >/dev/null <<EOF
# Generated by apply-jhn-mcp-token-fracta.sh — do not commit
COGENTIA_MCP_JHN_MUTATE=${MUTATE}
COGENTIA_MCP_JHN_TOKEN=${TOKEN}
COGENTIA_MCP_URL=${URL}
EOF
sudo chown root:ubuntu /srv/cogentia/secrets/jhn-mcp.env
sudo chmod 640 /srv/cogentia/secrets/jhn-mcp.env
sudo tee /etc/systemd/system/mcp-cogentia.service.d/jhn-mutate.conf >/dev/null <<'EOF'
[Service]
EnvironmentFile=-/srv/cogentia/secrets/jhn-mcp.env
EOF
# also keep copy in inseme/.env on node for local tools (optional line append)
if ! grep -q '^COGENTIA_MCP_JHN_TOKEN=' /srv/cogentia/repos/inseme/.env 2>/dev/null; then
  echo '' | sudo tee -a /srv/cogentia/repos/inseme/.env >/dev/null
  echo '# Cogentia MCP JHN (from apply-jhn-mcp-token-fracta)' | sudo tee -a /srv/cogentia/repos/inseme/.env >/dev/null
  echo \"COGENTIA_MCP_JHN_MUTATE=${MUTATE}\" | sudo tee -a /srv/cogentia/repos/inseme/.env >/dev/null
  echo \"COGENTIA_MCP_JHN_TOKEN=${TOKEN}\" | sudo tee -a /srv/cogentia/repos/inseme/.env >/dev/null
  echo \"COGENTIA_MCP_URL=${URL}\" | sudo tee -a /srv/cogentia/repos/inseme/.env >/dev/null
fi
sudo systemctl daemon-reload
sudo systemctl restart mcp-cogentia.service
sleep 2
systemctl is-active mcp-cogentia.service
# verify flag without printing token
systemctl show mcp-cogentia.service -p EnvironmentFiles --no-pager
curl -fsS -m 10 http://127.0.0.1:8791/health | head -c 200
echo
"

echo "OK — verify anonymously then with Authorization Bearer."
